# Generated by Django 6.0.7 on 2026-07-16 01:33

import casino.fields
import casino.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=64, verbose_name='Apellidos')),
                ('edad', models.PositiveSmallIntegerField(validators=[casino.models.validar_edad_mayoria], verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=16, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo'), ('union_libre', 'Unión libre')], max_length=24, verbose_name='Estado Civil')),
                ('saldo', casino.fields.EncryptedDecimalField(default=20000, help_text='Saldo cifrado en Guaraníes.', verbose_name='Saldo Disponible (Gs.)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('Bancospy', 'Banco de Paraguay'), ('Avanzar', 'Avanzar'), ('Regional', 'Regional'), ('Visión', 'Visión Banco'), ('Otros', 'Otros bancos')], max_length=32, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(max_length=32, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(max_length=32, verbose_name='Número de Cuenta')),
                ('titular', models.CharField(max_length=128, verbose_name='Nombre del Titular')),
                ('cedula', models.CharField(max_length=32, verbose_name='Cédula')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga'), ('retiro', 'Retiro')], max_length=12, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Monto (Gs.)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=16, verbose_name='Estado')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d', verbose_name='Comprobante')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
