# Generated by Django 6.0.7 on 2026-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='telefono',
            field=models.CharField(default='', max_length=32, verbose_name='Teléfono / WhatsApp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='recibio_regalo',
            field=models.BooleanField(default=False, help_text='Marca si el usuario obtuvo el regalo de los primeros registros.', verbose_name='Recibió bono de bienvenida'),
        ),
        migrations.AddField(
            model_name='player',
            name='slot_play_count',
            field=models.PositiveIntegerField(default=0, help_text='Contador acumulado de giros de tragamonedas para habilitar jackpots de retención.', verbose_name='Jugadas consecutivas de tragamonedas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='banco',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cedula',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Cédula'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=16, verbose_name='Estado de pago'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='telefono',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono / WhatsApp'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='titular',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre del Titular'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='banco',
            field=models.CharField(max_length=64, verbose_name='Banco de preferencia'),
        ),
    ]
