# Generated by Django 6.0.7 on 2026-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_bankaccount_telefono_player_recibio_regalo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='alias',
            field=models.CharField(blank=True, help_text='Ej. Ahorros personal', max_length=64, null=True, verbose_name='Alias'),
        ),
    ]
