# Generated by Django 6.0.7 on 2026-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_bankaccount_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Saldo de bono'),
        ),
        migrations.AddField(
            model_name='player',
            name='bonus_rollover',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Rollover acumulado'),
        ),
        migrations.AddField(
            model_name='player',
            name='bonus_rollover_target',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Meta de rollover'),
        ),
        migrations.AddField(
            model_name='player',
            name='free_spins',
            field=models.PositiveIntegerField(default=0, verbose_name='Giros gratis disponibles'),
        ),
    ]
